- LICENSE
- _config.yml
- _layouts/default.html
Added _layouts folder with updated template
Added title and desc to _config.yml
> Updated LICENSE to CC-BY 4.0 International

- _includes/youtubePlayer.html
- _sass/primer-layout/lib/container.scss
- common-requests/install.md
> Created basic page for all-in-one installation

- 404.html
@joewxboy This is a basic 404 page for issue https://github.com/open-horizon/open-horizon.github.io/issues/5
I have tested in local and it works well.
Signed-off-by: Xiulei Zhu <xiuleizh@cn.ibm.com>
> create 404 page

- _includes/code_snippet.md
- common-requests/contribute.md
- index.md
> added clipboard include and applied

- common-requests/install.md
- common-requests/use.md
- quick-start.md
@Rene-Ch1 could you please review for spelling, grammar, tone/voice, and whatever else you feel appropriate.
This will close issue #14
> Added use.md file and linked from install.md per issue-14

- quick-start.md
> fix: update quickstart description

- _includes/nav.html
- faq/anax.md
- faq/devops.md
- faq/examples.md
- faq/faq.md
- faq/general.md
- faq/management-hub.md
This is to address issue 18: https://github.com/open-horizon/open-horizon.github.io/issues/18
Signed-off-by: Xiulei Zhu <xiuleizh@cn.ibm.com>
> Issue 18: Create an initial FAQ Section

- _posts/2020-08-20-dedicated-network-between-services.md
- _posts/2020-08-24-installation-requirements.md
> Issue 18: Added two FAQ posts

- common-requests/report-an-issue.md
Fixes #16 
I based the documentation partially on https://wiki.lfedge.org/display/SDO/Reporting+Issues.
Signed-off-by: Clement Ng <clementdng@gmail.com>
> Issue 16: Populate report-an-issue.md

- common-requests/get-technical-support.md
Signed-off-by: Edidiong Etuk <edidiongmichael08@gmail.com>
Closes: #15
> Issue 15: Populated Get Technical Support

- common-requests/install.md
I've updated the install.md and install.html file. The links provided in the video for installation will directly be displayed for efficiency.
Signed-off-by: Piyush Thange <pthange19@gmail.com>
> Updating the install.md and adding some links used in the video.

- quick-start.md
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
Fixed issue : #41
> Added Link to Youtube playlist

- .gitignore
- docs/getting_started/overview_oh.md
- docs/hub/hub.md
- docs/images/edge/01_OH_overview.svg
- docs/images/edge/02a_Developing_AI_model_using_MMS.svg
- docs/images/edge/02b_Updating_AI_model_using_MMS.svg
- docs/images/edge/03a_Developing_edge_service_for_device.svg
- docs/images/edge/03b_Developing_edge_service_for_cluster.svg
- docs/images/edge/05a_Installing_edge_agent_on_device.svg
- docs/images/edge/05b_Installing_edge_agent_on_cluster.svg
- docs/images/edge/06_OH_management_hub_install.svg
- docs/index.html
- docs/using_edge_services/detailed_policy.md
Replaced IEAM and UI in images.
> Updated images

- dir.md
- docs/developing/container_registry.md
> added HTML linking page

- docs/getting_started/developer_learning_path.md
This PR is a continuation to #66 to improve the content presented in the learning page.
Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>
> Update the developer learning page

- Gemfile.lock
- README.md
- docs/getting_started/overview_oh.md
- docs/getting_started/overview_sm.md
- docs/index.html
Signed-off-by: Dave Booz <booz@us.ibm.com>
> Issue 78 - First pass at secrets manager doc updates

- css/custom.css
- docs/index.html
> issue 81 - Rectified docs page styling errors

- docs/user_management/security_privacy.md
Signed-off-by: Dave Booz <booz@us.ibm.com>
> Issue 92 - add malware statement to MMS doc

- .github/hacktoberfest 2021/Guidelines 2021.md
Signed-off-by: unnati914 <69121168+unnati914@users.noreply.github.com>
Fixes #105
> Added Guidelines.md 

- docs/getting_started/faq.md
Added click to copy functionality to the commands present on FAQ page
Fixes #139
code
locally by running on localhost: 4000
https://user-images.githubusercontent.com/64387054/153667068-e7f754f8-6e27-40aa-b586-18d1d8832ec2.mp4
> Issue-139 (Chore): Added Click to Copy functionality

- README.md
Added "Possible Errors that a new contributor" section in the readme.md and the `webrick` and `wdm` error for now 
Update #149
docs 
Locally in my local origin repo
> Issue-149 (Chore): Added Possible Errors section in the readme

- README.md
- Added status badges for GHA in README.md
- Added Matrix Chat Server link
Fixes #154 
> Added status badges for GHAs and Matrix Chat server link

- .github/ISSUE_TEMPLATE/check-broken-links.md
The broken link checker template was deleted in some previous commit, restored it back.
Related to #157 
...
> Added the template back, which was deleted in some previous commit

- .github/ISSUE_TEMPLATE/report-orphan-pages.md
- .github/workflows/orphan_pages_checker.yml
GHA that outputs the orphan pages in GHA logs on same interval as broken link checker.
Fixes #89 
Tested on my forked repo and locally
...
> Orphan pages checker GHA

- .github/workflows/anaxdocscopy.yml
- README.md
Added workflow status badge for orphan pages checker and fixed the name of `anaxdocscopy` Github action.
Related to #154 
...
> Added status badge for orphan-pages-checker

- common-requests/get-technical-support.md
updated slack links to "Element" on the technical support page
Fixes #166
code
locally by running it on the server
> Issue-166 (Chore): Updated Technical Support Page

- _includes/footer.html
Updated License in the footer section as it is not correct and not associated to open-horizon and made footer links external ( open in new tab)
Fixes #168
code 
tested locally by running server locally
> Issue-168 (Chore): Updated License and added external links

- README.md
> fixed the matrix chat link

- _layouts/page.html
- css/clean-blog.css
- docs/admin/accessing_logs.md
- docs/admin/backup_recovery.md
- docs/admin/index.md
- docs/admin/monitoring.md
- docs/admin/multi_tenancy.md
- docs/admin/troubleshooting.md
- docs/api/agbot_api.md
- docs/api/agent_api.md
- docs/api/index.md
- docs/cli/cloudctl_oc_cli.md
- docs/cli/exploring_hzn.md
- docs/cli/hzn_cli.md
- docs/cli/index.md
- docs/developing/best_practices.md
- docs/developing/cicd_process.md
- docs/developing/container_deployment_options.md
- docs/developing/container_registry.md
- docs/developing/cpu_msg_example.md
- docs/developing/creating_hello_world.md
- docs/developing/developing.md
- docs/developing/developing_clusters.md
- docs/developing/developing_details.md
- docs/developing/developing_secrets.md
- docs/developing/developingstart_example.md
- docs/developing/environment_variables.md
Fixes #151 
This pr is one of the addition to fix linked issue.
I would like feedback on whether I am making the right changes.
@joewxboy
> Issue-151: Changing Titles and Adding Description

- README.md
Updated local testing instructions
Fixes #178 
docs
locally in my forked repo's readme.
> Issue-178 (Docs): Updated local testing instructions

- docs/developing/cicd_process.md
Signed-off-by: Abhijay Jain [Abhijay007j@gmail.com](mailto:Abhijay007j@gmail.com)
Fixed Broken link for accessing UI 
Fixes #186 
code
locally by running server
> Issue-186 (Fix): Fixed broken link For accessing UI

- README.md
Fixes #209 
This PR Contains
* Added Contributors in Readme
> chore : added contributors in readme

- _config.yml
- _includes/ogmeta.html
Added missing link to `_config.yml` file to run tests.
Fixes #214 
code
locally by running command `bundle exec jekyll serve`
> Issue-214 (bug): Added missing link to `_config.yml` file

- docs/getting_started/faq.md
- docs/using_edge_services/policy_user_cases.md
Moved Deployment Policy FAQ entry to to "Deployment Policy Use Cases" page
Fixes #226 
docs and code 
tested locally on server
> Issue-226: (Docs) Moved Deployment Policy FAQ entry

- MAINTAINERS.md
Added @johnwalicki to MAINTAINERS.md for Documentation
Fixes #236 
...
> Issue-236: Added John

- docs/installing/adding_devices.md
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>
Added Support for Ubuntu 22.04 Jammy
Fixes #238  (issue)
> Issue-238: Added Support for Ubuntu 22.04 Jammy

- .github/workflows/codeql.yml
This PR Contains
- Added Codeql Gha for Code Analysis
> added codeql gha for code analysis

- docs/getting_started/faq.md
- docs/getting_started/known_issues.md
- docs/installing/adding_devices.md
Signed-off-by: Sonal Jain <sonaljain067@gmail.com>
This issue fixes Raspbian in documentation to Raspberry Pi OS
Fixes #222 
[✓] This change requires a documentation update
NA
...
- [✓] My code follows the style guidelines of this project
- [✓ ] I have made corresponding changes to the documentation
- [✓ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [✓ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the …
> Issue-222: Replace Raspbian references

- _data/keyword.yml
This PR defines the `rhel` keyword in the `keyword.yml` so that https://open-horizon.github.io/docs/installing/adding_devices.html renders correctly.
Fixes #243
> Issue-243: Define rhel keyword

- _config.yml
Signed-off-by: Joseph Pearson <joe.pearson@us.ibm.com>
Added SUMMARY.md and MAINTAINERS.md to the exclude configuration for GitHub Pages.
> Issue-253: updated GHP config to remove files from page gen

- README.md
> Added link to open horizon website

- docs/installing/adding_devices.md
Fixes #260  and lots of linter warnings
This is a sub-task of https://github.com/open-horizon/anax/issues/3228
...
> Issue-260: RHEL 8.6 support

- docs/admin/troubleshooting.md
- docs/developing/cicd_process.md
Fixed broken links
Fixes #240 , #229
locally by running on localhost
...
> issue-240 (chore) : Fixed broken links

- _data/keyword.yml
- docs/getting_started/known_issues.md
- docs/installing/adding_devices.md
- docs/installing/advanced_man_install.md
Add Fedora 36 to the documentation.  Fix some linter issues. Add Fedora keyword.
Fixes #266 
...
> Issue 266 - Fedora 36 support

- .github/workflows/orphan_pages_checker.yml
- common-requests/install.md
- docs/developing/further_reading.md
- docs/getting_started/accessibility.md
- docs/getting_started/overview_oh.md
- docs/hub/hub.md
- docs/hub/installation.md
- docs/hub/prerequisites.md
- docs/index.html
- docs/installing/installing_edge_nodes.md
Edited existing pages to provide links to the orphaned pages in reasonable locations.  Removed oauth2-redirect.html from the orphan check because you shouldn't be able to navigate to it.
Fixes #270 
I linked directly to the markdown pages using my editor's autocomplete feature to prevent typos.
...
@johnwalicki Let me know if you have any questions.
> Issue-270: edited pages and excluded oauth2

- docs/installing/edge_cluster_agent.md
Fixed ordered list numbering and code block indentation
Fixes #219 
Review https://open-horizon.github.io/docs/installing/edge_cluster_agent.html
...
> Issue 219: Fix ordered list / code blocks

- docs/developing/service_containers.md
- docs/developing/service_operators.md
- docs/hub/post_install.md
- docs/hub/prepare_for_edge_nodes.md
- docs/installing/adding_devices.md
- docs/installing/advanced_man_install.md
- docs/installing/many_install.md
- docs/troubleshoot/index.md
- Fix {{site.data.keyword.macos_notm}} keyword substitutions
- Widespread lint fixes
- Indent code blocks correctly
Fixes # 281
Visit
- https://open-horizon.github.io/docs/hub/prepare_for_edge_nodes.html
- https://open-horizon.github.io/docs/developing/service_operators.html
> Issue281 mac os

- docs/installing/adding_devices.md
- docs/installing/advanced_man_install.md
Changes:
- modified:   docs/installing/adding_devices.md
- modified:   docs/installing/advanced_man_install.md
Fixes : 
#284 - RHEL9 support
#262 - Intel only Macs 
Inspect the changes in:
- https://open-horizon.github.io/docs/installing/adding_devices.html
- https://open-horizon.github.io/docs/installing/advanced_man_install.html
> Issue 284 Add RHEL 9 support / Issue 262 Clarify Intel-only Macs

- docs/developing/best_practices.md
- docs/getting_started/developer_learning_path.md
- docs/getting_started/release_notes.md
- docs/installing/automated_install.md
- docs/user_management/disaster_recovery.md
This fixes all broken links **except** the SDO page.  That page requires a conversion of the instructions to a CLI-based approach.
Fixes #287 
...
@johnwalicki Take a look.  Node the SDO page is not fixed.  Two links removed entirely.  The IBM Research link has been replace since the original page with the cert issue was outdated anyways/
> Issue-287: Fixed broken links

- .gitignore
- docs/api/agbot_api.md
- docs/api/agent_api.md
- docs/api/index.md
Removed conditional logic, since it was invisible to downstream documentation-rendering logic.  Instead, recommend rule that transforms all URLs on the API index page that end with `.html` to substitute `.json` to resolve.
Fixes #291 
...
@johnwalicki See comment above.  Let me know if you have any questions.
> Issue-291: Backed out conditional logic

- docs/developing/further_reading_devices.md
- docs/developing/service_containers.md
- docs/getting_started/components.md
- docs/getting_started/faq.md
- docs/hub/cluster_sizing.md
- docs/hub/configuration.md
- docs/installing/advanced_man_install.md
- docs/installing/edge_cluster_agent.md
- docs/installing/many_install.md
- docs/installing/sdo.md
- docs/using_edge_services/cpu_load_example.md
- docs/using_edge_services/policy_user_cases.md
- docs/using_edge_services/service_rollbacks.md
This PR syncs some of the Open Horizon and IBM product documentation so they are in sync.
- Lint fixes, etc. 
Fixes #289 
Visit the following pages after the PR has been merged:
- https://open-horizon.github.io/docs/hub/cluster_sizing.html
- https://open-horizon.github.io/docs/developing/further_reading_devices.html
- https://open-horizon.github.io/docs/developing/service_containers.html
- https://open-horizon.github.io/docs/getting_started/faq.html
- https://open-horizon.github.io/docs/getting_started/components.html
- https://open-horizon.github.io/docs/hub/configuration.html
- …
> Issue289 syncdocs

- docs/developing/service_containers.md
- docs/installing/edge_cluster_agent.md
Ordered list formatting was incorrect on several pages and the numbered procedures were a mess. 
Fixes #294 
Visit
- https://open-horizon.github.io/docs/developing/service_containers.html
- https://open-horizon.github.io/docs/installing/edge_cluster_agent.html
...
> Issue 294: Fix ordered list formatting

- Gemfile.lock
- index.html
This PR Contains
fix formating of index.html file & fix grmmatical errors in index.html file
> chore : fix formating of index.html file & fix grmmatical errors in index.html file

- docs/developing/further_reading_devices.md
- docs/getting_started/known_issues.md
- docs/hub/overview.md
- docs/installing/adding_devices.md
- docs/installing/many_install.md
Fixes #301 
With the IEAM 4.4 product release, several documentation pages got updated with improved instructions.
In the interest of keeping the open source documentation in sync, this ticket will sweep in those updates:
-    Add a link to the Secrets Manager in the further_reading_devices.md
-    known_issues.md - additional caveats
-    hub overview.md - section title
-    adding_devices.md - ppc64 supported versions
-    many_install.md - highlight section
Visit these pages once the PR is merged:
- https://open-horizon.github.io/docs/getting_started/known_issues.html
- …
> Issue 301: sync OH docs

- Gemfile.lock
- _layouts/page.html
- css/clean-blog.css
- css/custom.css
- docs/anax/_layouts/page.html
- docs/anax/docs/_layouts/page.html
- docs/index.html
Signed-off-by: 03amir <as2437@it.jgec.ac.in>
...
> responsive-docs-page

- docs/devops/docs/README.md
Fixes https://github.com/open-horizon/devops/issues/120
> Pull devops from joewxboy fork

- docs/index.html
Added a new card for integrations and linked to where the Kubearmor docs will be.
...
@johnwalicki This addresses issue #305 once the Kubearmor index page has been published.
> Issue-305: Integrate Kubearmor docs into docs index page

- docs/index.html
Fixes #315 
Visit https://open-horizon.github.io/docs/ and follow the All-in-One link.
...
> Issue 315: Add All-in-One to index.html

- docs/index.html
Signed-off-by: Judith Kraziewicz <judith.kraziewicz@gmail.com>
...
> issue #318:[Documentation: Consistent index.html Card Titles]

- css/custom.css
- docs/index.html
This PR adds a link to the Open Horizon YouTube playlist. I also added `10px` to `min-height` in the `.doc-card` class in order to maintain the formatting since adding this item to the list expands the size of the card but not the others and misaligns the rows.
Fixes #325 
Changes were tested locally. 
1. Run the project locally 
2. Navigate to `localhost:4000/docs/`
3. In the 'Learning' card click 'Open Horizon Video playlist'
...
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] Any dependent changes have been merged and published in downstream modules
@johnwalicki …
> Add link to OH YouTube Playlist

- docs/api/agbot_api.md
- docs/api/agent_api.md
Fix two of the broken links discovered by the Broken Link scanner.  Both broken links were related to the anax documentation moves.
Fixes #322 (partial)
Visit 
- https://open-horizon.github.io/docs/api/agent_api.html
- https://open-horizon.github.io/docs/api/agbot_api.html
...
> Issue #322: Fix broken anax docs link

- docs/installing/adding_devices.md
- docs/installing/many_install.md
Updated links to brew install instructions on a reputable site that isn't down.
Fixes #333 
...
Closes issue #333
> Issue-333: Updated links with brew instructions

- docs/api/agent_api.md
Signed-off-by: Dipesh Rawat <Dipesh.rawat@ibm.com>
This PR contains the changes to fix the subtitle description for the page https://open-horizon.github.io/docs/api/agent_api.html
Fixes #331 (also, #332)
Changes were tested locally.
- Run the project locally
- Navigate to localhost:4000/docs/api/agent_api.html
...
> Issue#331: Fix for the page subtitle description text

- docs/mgmt-hub/docs/index.md
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>
Fixed the hyperlink format to markdown. 
Fixes https://github.com/open-horizon/open-horizon.github.io/issues/338
Manually verification
...
> Issue 338 - fixed hyperlink format

- docs/troubleshoot/index.md
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>
Added new common issue with deploy-mgmt-hub.sh to troubleshoot page
Fixes https://github.com/open-horizon/open-horizon.github.io/issues/346
Test by running the site locally
...
> Issue 346 - Added new common issue with deploy-mgmt-hub.sh

- docs/installing/adding_devices.md
Add Fedora 37 as a supported release
Fixes #353
Tested on a Fedora 37 aarch64 Raspberry Pi device
...
- [x ] I have made corresponding changes to the documentation
> Issue #353 - Fedora 37 support

- docs/index.html
Fixes #359  #352 #215 #351
Visit https://open-horizon.github.io/docs/
...
> Issue #359 - Updates to Docs main index.html

- docs/index.html
Fixes #363 
Visit https://open-horizon.github.io/docs/
...
> Issue #363 - Fix OH Docs main index card alignment

- docs/getting_started/components.md
- docs/installing/adding_devices.md
Refresh the Getting Started components table.
Fixes #370
> Issue370 - Getting Started components table

- docs/installing/adding_devices.md
Fix the Jetson TX2 broken link
Fixes #368 
Visit https://open-horizon.github.io/docs/installing/adding_devices.html and check the link.
...
> Issue 368 - Fix Jetson TX2 broken link

- docs/installing/adding_devices.md
Fixes #373 
Visit https://open-horizon.github.io/docs/installing/adding_devices.html
> Issue #373 - Refresh Adding Devices page

- docs/developing/examples.md
Fixes #372
The start of an Examples Landing page.  There's more work to be done.
> Issue #372 - Examples landing page

- _config.yml
- docs/developing/environment_variables.md
- docs/installing/adding_devices.md
- docs/installing/automated_install.md
Fixed accessing_ui link by removing that sentence.
Fixed broken FAQ link in header.
Changed environment variable link from pointing to GitHub MD file to the actual generated page.
Will need separate issue to fix broken link in anax repo.
Fixes #368 
```bash
git clone https://github.com/joewxboy/open-horizon.github.io.git
cd open-horizon.github.io
git checkout issue-368
make init
make run
```
Then browse the pages at http://localhost:4000/
...
> Issue-368: Fixing broken links

- _config.yml
- _includes/components/search_header.html
- _includes/head_custom.html
- _includes/open-horizon-navbar-logo.html
- _sass/color_schemes/open-horizon-theme.scss
This PR contains the changes regarding to changing the theme from lavender color to blue and adding logo in nav bar
Fixes #381
Changes were tested locally.
- Made the necessary changes
- Run the project locally
- Navigate to localhost:4000
> Issue #381: Changed the theme color and added logo

- _includes/head_custom.html
- _includes/open-horizon-navbar-logo.html
Signed-off-by: Dipesh Rawat <Dipesh.rawat@ibm.com>
Fixes https://github.com/open-horizon/open-horizon.github.io/issues/383
Visit https://open-horizon.github.io/ in the Firefox, Chrome and Safari browser.
...
> Issue #383:  Open Horizon logo and navbar search fix

- docs/anax/docs/agreement_bot_api.md
Signed-off-by: John Walicki <walicki@us.ibm.com>
Experiment with liquid syntax in a table
> Fix a table caption

- docs/installing/adding_devices.md
Fixes #392 
Review https://open-horizon.github.io/docs/installing/adding_devices/
...
> Issue #392 - Support for Mac arm64 M1/M2

- docs/getting_started/developer_learning_path.md
- docs/getting_started/overview_oh.md
- docs/getting_started/overview_sm.md
- docs/index.html
- quick-start.md
Fixes #394 
- Fix most of the broken links caused by the new theme
- Some lint fixes
- Update copyright and last updated fields in front matter
...
> Issue #394 - Fix broken links

- docs/api/agbot_secure_api.json
- docs/api/exchange_swagger.json
- docs/api/fdo_swagger.html
- docs/api/fdo_swagger.json
- docs/api/mms_swagger.json
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
Updated Agbot, Exchange, and MMS Swagger JSON files. Added FDO Swagger.
Fixes #398 
...
> Updated Agbot, Exchange, and MMS Swagger JSON files. Added FDO Swagger.

- docs/api/index.md
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
Fixes #397 
...
> Issue #397 - Updated main index with FDO link

- README.md
- docs/installing/edge_cluster_agent.md
Fixes #406 
Review: 
- https://open-horizon.github.io/docs/installing/edge_cluster_agent/
...
> Issue406 edgeclusteragent

- docs/developing/developing.md
- docs/developing/developing_details.md
- docs/developing/developing_secrets.md
- docs/developing/examples.md
- docs/getting_started/developer_learning_path.md
Fixes #408 
- Consistent top level headers
- copyright updates
- Page title modifications for the nav structure
View these pages at:
- https://open-horizon.github.io/docs/developing/
- https://open-horizon.github.io/docs/getting_started/developer_learning_path/
> Issue 408 - Consistent top level headers

- docs/developing/model_management_details.md
- docs/developing/transform_image.md
Fixes #410 
- Indentation for correct numeration and code blocks
- Add language to code blocks and replace non breaking space with regular spaces for consistency
- copyright updates
View these pages at:
- https://open-horizon.github.io/docs/developing/transform_image/
- https://open-horizon.github.io/docs/developing/model_management_details/
> Issue 410 - broken numeration and code blocks

- docs/developing/developing_secrets.md
- docs/developing/further_reading.md
- docs/developing/secrets_details.md
- docs/getting_started/overview_sm.md
Fixes #412
Visit / Review:
-    https://open-horizon.github.io/docs/getting_started/overview_sm/
-    https://open-horizon.github.io/docs/developing/secrets_details/
-    https://open-horizon.github.io/docs/developing/developing_secrets/
...
> Issue #412 - Navigation: Secrets Manager section

- docs/installing/adding_devices.md
Fixes #417
Visit - https://open-horizon.github.io/docs/installing/adding_devices/#proc-mac
...
> Issue #417 - Mac install instructions

- docs/installing/adding_devices.md
- docs/installing/advanced_man_install.md
Fixes #419
Fixes some link directives
Change the title of the Manual Install instructions in the left navigation.
> Issue #419 - Mac install links

- docs/getting_started/developer_learning_path.md
- quick-start.md
Fixed broken links in two files, updated timestamp, added external link directives.
Fixes #394 
...
This closes #394
> Issue-394: Fixed broken links, added external link directives

- docs/getting_started/developer_learning_path.md
Fixed broken link.
Indent on ordered list incorrect, fixed.
...
@johnwalicki  You were right about not linking to the .md file.
> Issue-394: Link still broken, bulleted list incorrect

- docs/admin/backup_recovery.md
- docs/hub/cluster_sizing.md
- docs/hub/gather_files.md
- docs/installing/fdo.md
- docs/installing/many_install.md
- docs/installing/preparing_edge_cluster.md
- docs/installing/registration.md
- docs/installing/sdo.md
Fixes #426 
- Several pages were not included in the navigation sidebar. This issue adds FDO (a new page), SDO, many_install.
- It fixes up pages that mention SDO (now also mention FDO with links)
- Some other random lint fixes that have been untracked on my clone. Finally pushing them via this issue.
Visit these new pages under **https://open-horizon.github.io/docs/installing/edge_devices/**
...
- [x I have tagged the reviewers in a comment below incase my pull request is ready for a review
> Issue #426 - Add FDO / SDO / Bulk Install docs to navigation

- docs/developing/developing.md
- docs/developing/developing_secrets.md
Fixes #429
Visit and confirm:
-    https://open-horizon.github.io/docs/developing/developing/
-    https://open-horizon.github.io/docs/developing/developing_secrets/
...
> Issue #429 - Add Title headers and descriptions

- docs/installing/fdo.md
- docs/installing/many_install.md
- docs/installing/sdo.md
Fixes #426 (continuation)
- Add preprocessor title directives to the front matter so that these pages appear in the left navigation
Visit this page and obverse its children in the left nav
- https://open-horizon.github.io/docs/installing/edge_devices/
> Issue #426 - Add FDO/SDO/Bulk agent install navigation titles

- docs/installing/registration.md
- docs/installing/watson_speech.md
Fixes #435 
- Add a link to https://github.com/open-horizon/open-horizon.github.io/issues/435
- Fix spelling errors
- Lint fixes
Visit : https://open-horizon.github.io/docs/installing/registration/
...
> Issue #435 - anax-in-container as an 'Installing the agent' option

- _sass/custom/custom.scss
- css/custom.css
Added the former rule for .externalLink class from custom.css (legacy) to Just the Docs's custom.scss file.
Fixes #434 
Ran the local preview before and after fix.
...
> Issue-434: Added custom CSS rule for external links

- docs/developing/developing_clusters.md
- docs/getting_started/overview_oh.md
- docs/hub/hub.md
- docs/installing/edge_clusters.md
- docs/installing/edge_devices.md
Fixes #442 
The following files are changed:
-  docs/developing/developing_clusters.md
-  docs/getting_started/overview_oh.md
-  docs/hub/hub.md
-  docs/installing/edge_clusters.md
-  docs/installing/edge_devices.md
Visit the following pages and make certain that the images load correctly:
- https://open-horizon.github.io/docs/developing/developing_clusters/
- https://open-horizon.github.io/docs/getting_started/overview_oh/
- https://open-horizon.github.io/docs/hub/hub/
- https://open-horizon.github.io/docs/installing/edge_clusters/
- https://open-horizon.github.io/docs/installing/edge_devices/
...
> Issue #442 - change <img src> tags from html to markdown

- docs/hub/hub.md
- docs/installing/edge_devices.md
Fixes #442 - continuation of fixing the image links from html to markdown
> Issue #442 - Fix img links

- docs/hub/lfedge_mgmt_hub.md
Change the full https:// URL to internal references using relative paths to the file.
Fixes #452 
> Issue #452: Change the links with URL to internal references

- docs/developing/container_deployment_options.md
- docs/installing/fdo.md
- docs/installing/sdo.md
- docs/integrating_index.html
Fixes #450 
Fixes $448
- I believe this will be the last PR related to externalLinks
- Resolves issues posted in https://github.com/open-horizon/open-horizon.github.io/issues/450#issuecomment-1446573765
Visit:
-  https://open-horizon.github.io/docs/developing/container_deployment_options/ (broken link)
-  https://open-horizon.github.io/docs/installing/fdo/ (missing a spacer between link and glyph)
-  https://open-horizon.github.io/docs/integrating_index/ (broken link)
> Issue #450 - Fix doc and image links

- docs/integrating_index.html
Fixes #449 
Now that the KubeArmor issue to fix the front matter navigation sidebar and External Links has been fixed / merged (see https://github.com/open-horizon/kubearmor-integration/issues/20 ) the link moved / broke again.
This PR adjusts the link.
Visit: 
- https://open-horizon.github.io/docs/integrating_index/
- https://open-horizon.github.io/docs/kubearmor-integration/docs/README/
> Issue #449 - Fix KubeArmor Integration link

- docs/index.html
> Issue-462: Fixing broken link

- README.md
- docs/troubleshoot/index.md
Added an explanation about how some  documentation are source from different repo. 
Fixes #348
Test by running the site locally
...
> Issue 348 - Adding explanation on docs source repo

- docs/developing/best_practices.md
- docs/developing/cicd_process.md
- docs/developing/container_deployment_options.md
- docs/developing/container_registry.md
- docs/developing/creating_hello_world.md
- docs/developing/developing.md
- docs/developing/developing_clusters.md
- docs/developing/developing_details.md
- docs/developing/developingstart_example.md
- docs/developing/environment_variables.md
- docs/developing/examples.md
- docs/developing/further_reading.md
- docs/developing/further_reading_devices.md
- docs/developing/model_management_details.md
- docs/developing/model_management_system.md
- docs/developing/service_containers.md
- docs/developing/service_operators.md
- docs/developing/transform_image.md
- docs/getting_started/overview_sm.md
- docs/using_edge_services/service_rollbacks.md
Fixes #470 
Fixes #437 
Restructure the "Developing Edge Services" navigation and sub-navigation
Check all of the navigation under https://open-horizon.github.io/docs/developing/
...
> Issue #470 - Developing Edge Services navigation

- .github/workflows/orphan_pages_checker.yml
Updated GHA to use Ruby 3.0.4p208 instead of Ruby 2.6
Fixes #464 
...
I don't know of any way to test this other than to merge and manually run.
> Issue-464: Updating orphan pages checker due to ruby errors

- MAINTAINERS.md
Fixes #481 
Change my email address
> Issue #481 - Update MAINTAINERS.md email address

- docs/troubleshoot/support.md
Replaced the documentation on the Support page with more useful and detailed content
Fixes #479 
Before: 
After:
...
> Replace the original content on the Support page with More Detailed and Relevant Documentation

- docs/getting_started/components.md
Fixes #469 
Component table refresh
Visit this page: https://open-horizon.github.io/docs/getting_started/components/
...
> Issue #469 - Refresh component table

- docs/administering_index.html
- docs/index.html
- index.html
Added links to /docs/ and /quick-start/ to the home page body text.
Added a link to the RBAC page under administration - security in the security index page.
Fixes #490 
...
> Issue-490: add contextual links for orphan pages in-line.

- docs/user_management/rbac.md
- docs/user_management/security.md
- docs/user_management/security_privacy.md
- index.md
Replaced references in hyperlinks from absolute URIs to relative markdown file links.
Fixes #497 
...
@Rene-Ch1 please take a look
> Issue-497: Added/changed explicit links to MD files

- docs/installing/adding_devices.md
Fixes #500
Add RHEL 8.8 support to docs.
View the https://open-horizon.github.io/docs/installing/adding_devices/ page
> Issue #500 - Add support for RHEL 8.8 to Edge Devices doc

- docs/installing/adding_devices.md
Add support for RHEL 9.2 and Fedora 38 to the documentation.  Earlier PRs added these distro versions to agent-install.sh
Fixes #502
Visit
https://open-horizon.github.io/docs/installing/adding_devices/
...
> Issue #502 - RHEL 9.2 and Fedora 38 distro support

- _config.yml
- dir.md
> Issue-504: modified two existing links

- _sass/layout.scss
> fixes #523

- Gemfile.lock
- Makefile
- _config.yml
Add LF Edge ref to the footer on the docs site
Fixes #525  
@joewxboy
> Add LF Edge reference in docs footer

- README.md
- docs/demos/index.md
- docs/index.html
> Issue-542: Demos landing page

- docs/demos/edgelake.md
- docs/demos/skupper.md
> Issue 549: Added demo videos

- docs/demos/mlops.md
> Issue 551: Added video to MLOps demo page

- docs/demos/kubearmor.md
- docs/demos/mlops.md
> Issue 553: Added KubeArmor and MLOps videos

- docs/demos/edgelake.md
- docs/demos/kubearmor.md
- docs/demos/mlops.md
- docs/demos/openbao.md
- docs/demos/skupper.md
> Issue 555: added 1 minute demos

- docs/demos/fdo.md
> Issue 557: Added FDO videos and chart

- docs/demos/openbao.md
> Issue 559: updates secrets demo video link

- docs/demos/edgelake.md
> Issue-561: Added joint architecture links to EdgeLake page

- quick-start.md
> Issue 583: Updated quickstart page to specify Ubuntu 24

- docs/user_management/rbac.md
- docs/user_management/security.md
> Issue-587: Changed rbac reference

- docs/user_management/security.md
- docs/user_management/security_privacy.md
> Issue 589: Added another link to RBAC

- docs/admin/multi_tenancy.md
Changed page title typo from `multitenacy` to `multi-tenancy`
Fixes #602 
...
@johnwalicki
> Issue 602: Fix typo

- docs/getting_started/release_notes.md
- Add a link to the Building a Release page
Fixes #605
Visit https://open-horizon.github.io/docs/getting_started/release_notes/
...
> Issue #605 - Add link to Building a Release page

- docs/getting_started/release_notes.md
Fixes #605
Change the markdown
...
> Issue #605 - Fix link to Building a Release page

- docs/installing/adding_devices.md
- docs/installing/many_install.md
Added some new operating systems and corrected an issue with the bulk install
Updated documentation
...
> update support and fix correct bulk install

- _config.yml
Fixes #609 
Footer updates:
- Change the copyright to 2025
- Remove dead directories that are no longer in the repo
- Change the LF Wiki link to avoid a redirect.
> Issue #609 - Update Copyright to 2025

- docs/troubleshoot/index.md
Obsolete information regarding Podman was removed
...
> Remove obsolete Podman info

- docs/installing/adding_devices.md
Remove embedded supported env and point to actual source.
Fixes #624 
...
> Issue 624: sync requirements
