open-horizon/open-horizon.github.io

_includes/nav.html, _posts/2020-08-18-restart-agent.md, faq/index.md
I renamed the faq page as index.md so it would be available at /faq/ and created a post in `_posts` of type post with a tag of agent, then modified the FAQ index page to iterate over the tags to display.
The posts layout template is wrong and there are some formatting issues, but it appears that this approach works.
=> issue-18 FAQ pages as posts with tags

common-requests/install.md
The ">" symbol was interpreted in markdown as a blockquote element, as seen below.
The intent is for the text to state ">= 4GB RAM", as seen below.
Signed-off-by: Clement Ng <clementdng@gmail.com>
=> FIX: Escape the greater than sign in the installation prereqs

common-requests/use.md
Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>
This is a possible fix to issue #50 which preserves syntax highlighting as well as expands the ` ```json ` response blocks.
=> Expands rendered json blocks

docs/index.html
Signed-off-by: Anthony Mangiacapra <tonymang72@gmail.com>
This is a draft solution for issue #73 
An imported file, `www.css`, overwrites the `line-height` and `font-weight` values being used by other pages of the same type, which results in the differences on this specific page. This file is necessary for the formatting of other parts of the page, however manually overwriting `line-height` and `font-weight` to the correct values fixes the problem on the surface. It was also included twice on consecutive lines, so I've deleted the duplicate.
This contains one solution, specific to this file, however another solution would be to assign `line-height` and `font-weight` in `_layouts/page.html` for the specific line being affected here. This would have the same affect and doesn't change the …
=> Fixed overlapping text in header

_data/keyword.yml, docs/api/agbot_api.md, docs/developing/secrets_details.md, docs/getting_started/faq.md, docs/hub/cluster_sizing.md, docs/installing/edge_clusters.md, docs/installing/edge_devices.md, docs/installing/exchange_api.md, docs/troubleshoot/index.md, docs/user_management/rbac.md, docs/user_management/security_privacy.md, docs/using_edge_services/service_rollbacks.md
Modify all of the documentation markdown files that use `Agbot` as prose.  Substitute the usage of  `agbot`, `AgBot`, `Agbot` with a `Agbot`  keyword.  Skip the few use cases where agbot is used as part of the `hzn agbot` command or part of a OpenShift container name.
The keyword will not be translated.  The Agbot keyword is a "proper noun" so capitalized.  The documentation was very inconsistent in usage.
Fixes #204 
- [x ] This change required a documentation update
=> Issue-204: Agbot keyword variable fixes

docs/getting_started/document_conventions.md
I noticed that there is a typo in the document_conventions.md that caused the ### Examples header to render as markdown instead of a subheader in the html file.
The fix was to remove a leading space. I also fixed several other lint warnings on this page.
Fixes #247
=> Issue-247: document_conventions.md lint fixes

.github/workflows/orphan_pages_checker.yml
The Orphan Page Checker GHA does not contain an exclude list.  As a temporary fix, I've taken the diff statement that compares the site links to the physical files and piped it through a grep exclusion for the two exceptions.  Clearly, this approach is not scalable long-term.
Fixes # Issue #245 
I have not found a way to test GHAs.
...
@johnwalicki If you're OK with this approach and I haven't made a mistake, please review and approve.
=> Issue-245: Excluded two files

_data/keyword.yml
Add the `linux_ppc64le_notm` keyword substitution for `Linux ppc64le` to `_data/keyword.yml`
Fixes #263
Add the new Linux ppc64le keyword stanza to `_data/keyword.yml` file
View the  ppc64le section in https://open-horizon.github.io/docs/installing/adding_devices.html
...
=> Issue-263: Add ppc64le keyword

docs/api/index.md, docs/user_management/security.md
Added links for three new "user management" pages to the services.html page in that folder, since it appeared to be the index page.
Changes API links from JSON to interactive Swagger pages **only** for Open Horizon docs using Liquid Templating conditional logic: https://shopify.github.io/liquid/tags/control-flow/
Fixes #275 
Ran locally on doc server.
```
make init
make dev
make build
make run
```
open http://localhost:4000/docs/user_management/security.html, see "certificates", "disaster recovery", "monitoring" links.
open http://localhost:4000/docs/api/index.html, see "Agbot User API" and "Exchange API" links.
...
@johnwalicki and @Rene-Ch1 let me know if you have any questions.
=> Issue-275: added conditional logic, user management links to remove orphan page issue

docs/cli/hzn_cli.md, docs/developing/developingstart_example.md, docs/getting_started/document_conventions.md, docs/getting_started/release_notes.md, docs/installing/edge_cluster_agent.md, docs/installing/sdo.md
Partial sync of the hzn_cli.md between the Open Horizon Docs and the IBM Edge Application Manager docs.  I converged them to the extent possible. Closer but not 100%
I also took the opportunity to sync several other Open Horizon documents with some of the IEAM 4.3.3 documentation changes.
Fixes #219 
View these rendered pages on the OH docs site:
- https://open-horizon.github.io/docs/cli/hzn_cli.html
- https://open-horizon.github.io/docs/getting_started/release_notes.html
- https://open-horizon.github.io/docs/getting_started/document_conventions.html
- https://open-horizon.github.io/docs/installing/edge_cluster_agent.html
- https://open-horizon.github.io/docs/installing/sdo.html
...
=> Issue 219: Sync Docs

docs/index.html
With the migration to Just the Docs formatting, the index.html landing page has broken links.  This PR changes the links.
Fixes #379
- [x ] This change requires a documentation update
Visit https://open-horizon.github.io/docs/ and test the links.
...
=> Issue #379 - Fix index.html broken links

_includes/components/aux_nav.html, _includes/head_custom.html, _includes/open-horizon-navbar-logo.html
Signed-off-by: Dipesh Rawat <Dipesh.rawat@ibm.com>
Added option to toggle dark and light theme mode via button in the navbar.
Fixes #399
Visit https://open-horizon.github.io/ in the browser
- Theme toggle button in navbar
- Dark mode theme preview
- Theme in different browser
...
=> Issue #399: Add option to toggle dark and light theme mode

Gemfile.lock, Makefile, quick-start.md
Updated the Quick Start page to specify/clarify what is installed with "all-in-one" and to also have instructions for installing just the agent, which is applicable to those using the LF Edge Community Lab instance.  This will make it easier for new users and prevent admins from having to email agent install instructions.
Fixes #416 
I generated the documentation locally and viewed the page.
...
@johnwalicki hopefully this doesn't add complexity, since the purpose is to simplify.  I also noticed that the env vars have significantly different path values from the agent installation docs elsewhere.  We may need to look into that later.  These values are what I send to all new Community Lab users, and are verified correct.
@Rene-Ch1 Let me know if …
=> Issue-416: added install instructions for just the agent

docs/admin/accessing_logs.md, docs/installing/fdo.md, docs/installing/watson_speech.md, docs/troubleshoot/troubleshooting.md, docs/user_management/gdpr.md, docs/using_edge_services/cpu_load_example.md, docs/using_edge_services/using_patterns.md
Fixes #432 
- fix Lint warnings
=> Issue #432 - fix lint warnings

Gemfile.lock, docs/index.html
Issue 480: I have created a layout for the docs page that now has two columns with the boxes side by side when the browser is wide enough. When the browser is shrunk, the two columns stack into a single column. @joewxboy 
I ran this locally to ensure that the changes worked. Tested functionality as the screen shrunk to find a working solution.
=> Issue 480: Create two columns on the Docs page

docs/installing/edge_cluster_agent.md, docs/installing/edge_clusters.md, docs/installing/install_k3s_edge_cluster.md, docs/installing/install_microk8s_edge_cluster.md, docs/installing/install_ocp_edge_cluster.md, docs/installing/preparing_edge_cluster.md, docs/using_edge_services/deploying_services_cluster.md, docs/using_edge_services/removing_agent_from_cluster.md
Updated the last modified headers on the changed pages.  Added navigation links to the appropriate pages.  Did NOT divide installing the cluster agent sections into separate pages.  Will instead put behind tabbed navigation on a single page when we migrate to Docusaurus.  Just The Docs does not have this type of navigation widget.
Fixes #564 
...
=> Issue 564: Refactor navigation on cluster installation pages

docs/installing/install_k3s_edge_cluster.md, docs/installing/install_microk8s_edge_cluster.md, docs/installing/install_ocp_edge_cluster.md
Fixes #572 
Related to Issue #564 and PR #571 , the new pages do not appear in the navigation. The fix is to add the appropriate `grand_parent:` directive tags to those updated pages:
-  install_k3s_edge_cluster.md
-  install_microk8s_edge_cluster.md
-  install_ocp_edge_cluster.md
Visit https://open-horizon.github.io/docs/installing/preparing_edge_cluster/ and its child pages after the PR has been merged.
...
=> Issue #572 - Set navigation grand parent

docs/index.html, docs/using_edge_services/service_rollbacks.md
Updated the existing rollback docs page to make it clearer that this also updates existing deployed services, and providing a link to an example policy.  Also updating the main index to add a link to this page.
Fixes #614 
...
This was for the Edge Lake team at their request.
=> Issue 614: updating docs for deployment policy auto updating

docs/installing/edge_cluster_agent.md
Update the edge cluster agent installation documentation:
- Modified the architecture prerequisites to include AMD64, ARM64, ppc64le, and s390x.
- Adjusted the indentation of Notes to ensure proper Markdown formatting.
- Fixed minor typos in commands and descriptions.
Fixes #649
- Checked Markdown rendering locally to ensure proper numbering and formatting.
- Verified code snippets run without errors when executed.
- None
=> Update edge cluster agent prerequisites and notes

docs/installing/fdo.md
Added a new bullet point under the **FDO overview** section in `docs/installing/fdo.md`.  
The new bullet describes the `start-rv.sh` script, which sets up a development version of the FDO Rendezvous server. This provides a way to test the onboarding process and voucher exchange before deploying FDO-enabled devices.
- Verified that the documentation renders correctly in Markdown format.
- Checked that the new bullet appears as the 4th item in the FDO overview list.
N/A
=> add a new bullet
